{% set name = "zxpy" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zxpy-{{ version }}.tar.gz
  sha256: d4856b617206e3664585e51ad30834cdbf9447f73b577b3af29326c91ee76efa

build:
  number: 0
  entry_points:
    - zxpy=zx:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - pyreadline3  # [win]
    - python

test:
  imports:
    - zx
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Shell scripts made simple
  home: https://github.com/tusharsadhwani/zxpy
  license: MIT
  license_file: LICENSE
  description: |
    Inspired by Google's zx, but made much simpler and more accessible using
     Python. While Bash is cool, and it's extremely powerful when paired with
     linux coreutils and pipes. But apart from that, it's a whole another
     language to learn, and has a (comparatively) unintuitive syntax for things
     like conditionals and loops. zxpy aims to supercharge bash by allowing you
     to write scripts in Python, but with native support for bash commands and
     pipes.

extra:
  recipe-maintainers:
    - thewchan
